# Generated by Django 3.2.5 on 2021-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=20)),
                ('assignee', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
