# Generated by Django 3.2.5 on 2021-07-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ticketApp", "0002_auto_20210724_1734")]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="type",
            field=models.CharField(default="", max_length=10),
        )
    ]
